apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aotqei826-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aotqei826-go 
  name: aotqei826-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aotqei826-go 
